services:
  app:
    build: .
    ports:
      - "5000:5000"
    end_file: .env
    entrypoint:
    - sleep
    - infinity
    image: docker-fast-api
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

